// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataApi.Entity.Models
{
    public partial class StudentDetails
    {
        [Key]
        public int StudentId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string PhoneNum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedTimeStamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdateTimeStamp { get; set; }
        public bool? Is_deleted { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ReTypePassword { get; set; }
        public int? LocationId { get; set; }

        [ForeignKey("LocationId")]
        [InverseProperty("StudentDetails")]
        public virtual PhoneDetail Location { get; set; }
    }
}